[build]
publish = "public"
functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200

[[redirects]]
  from = "/og.html"
  to = "/og.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/tiles/*"
  [headers.values]
    Content-Type = "application/x-protobuf"
    Access-Control-Allow-Origin = "*"
